"""Add status to Betslip

Revision ID: 1736bef3cd7c
Revises: d56c35030c32
Create Date: 2025-07-20 14:26:19.543266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1736bef3cd7c'
down_revision = 'd56c35030c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.drop_index('ix_betslips_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betslips', schema=None) as batch_op:
        batch_op.create_index('ix_betslips_id', ['id'], unique=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
