"""Add status column to Betslip

Revision ID: 3c168d53aae6
Revises: e8b632b264b9
Create Date: 2025-07-20 12:11:16.267184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c168d53aae6'
down_revision = 'e8b632b264b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betslip', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
