"""Add display_order to Ad

Revision ID: e8b632b264b9
Revises: 87827a008784
Create Date: 2025-07-20 11:08:47.001822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b632b264b9'
down_revision = '87827a008784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
